export const exampleData: string[] = [
     '🤖 AI Trends 2024',
     '🚀 Space Exploration Updates',
     '🎮 Gaming News',
     '📈 Stock Market Insights',
     '🎥 Movie Recommendations',
     '📚 Book Summaries',
     '🍴 Best Recipes',
     '🌍 Global News',
     '🎵 Music Hits',
     '🏀 Sports Highlights',
     '🎨 Art Exhibitions',
     '🧩 Puzzle of the Day',
     '💡 Innovative Ideas',
     '💵 Financial Tips',
     '🏡 Home Decor',
     '👗 Fashion Trends',
     '🚗 Car Reviews',
     '📱 Gadget Reviews',
     '🌱 Gardening Tips',
     '🐾 Pet Care Advice',
];
